"""empty message

Revision ID: 30e4b123d2d5
Revises: 
Create Date: 2020-07-15 09:45:46.712458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e4b123d2d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('gender_pref', sa.String(length=20), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('spectrum', sa.String(length=20), nullable=False),
    sa.Column('likes_puns', sa.Boolean(), nullable=True),
    sa.Column('favorite_pet', sa.String(length=20), nullable=True),
    sa.Column('spontaneous', sa.Boolean(), nullable=True),
    sa.Column('into_tech', sa.Boolean(), nullable=True),
    sa.Column('introvert', sa.Boolean(), nullable=True),
    sa.Column('liked_users', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('blocked_users', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('users')
    # ### end Alembic commands ###
